<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>
	<ItemGroup>
    <PackageReference Include="Microsoft.SqlServer.DacFx" Version="170.5.96" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\BinaryDataDecoders.ToolKit\BinaryDataDecoders.ToolKit.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Update="GitVersion.MsBuild" Version="6.8.2">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

</Project>
